// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLHQxCKAo_5BIPLCU_yt9dbe0-wUeRSwk',
    appId: '1:1005128813885:web:84f2453028840b4d090954',
    messagingSenderId: '1005128813885',
    projectId: 'msprohelp',
    authDomain: 'msprohelp.firebaseapp.com',
    storageBucket: 'msprohelp.appspot.com',
    measurementId: 'G-RY9YD6403P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Heccu8vZK5s3tk9uyYbiYmtmRQYrw68',
    appId: '1:1005128813885:android:1d10778a7b224480090954',
    messagingSenderId: '1005128813885',
    projectId: 'msprohelp',
    storageBucket: 'msprohelp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXW8aN01kqdfiMmrYH3JSfeDa4ngO5kbQ',
    appId: '1:1005128813885:ios:4c07d5b8c173c25e090954',
    messagingSenderId: '1005128813885',
    projectId: 'msprohelp',
    storageBucket: 'msprohelp.appspot.com',
    iosBundleId: 'com.example.nomDuProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXW8aN01kqdfiMmrYH3JSfeDa4ngO5kbQ',
    appId: '1:1005128813885:ios:715579a748f9e0c8090954',
    messagingSenderId: '1005128813885',
    projectId: 'msprohelp',
    storageBucket: 'msprohelp.appspot.com',
    iosBundleId: 'com.example.nomDuProjet.RunnerTests',
  );
}
